keep_and_rename:
  season: season
  season_type: season_type
  team: team
  conference: conference
  opponent: opponent
  game_id: game_id
  player_id: player_id
  player: player
  position: position
  completions: pass_cmp
  attempts: pass_att
  passing_yards: pass_yds
  passing_tds: pass_td
  interceptions: pass_int
  sacks: sacks
  rushing_attempts: rush_att
  rushing_yards: rush_yds
  rushing_tds: rush_td
  receptions: rec
  receiving_yards: rec_yds
  receiving_tds: rec_td

derived_metrics:
  - name: pass_yards_per_att
    expr: passing_yards / attempts
  - name: td_rate
    expr: passing_tds / attempts
  - name: int_rate
    expr: interceptions / attempts

positions_allowed:
  - QB
  - RB
  - WR
  - TE
