name: Build Modeling Dataset (Situational)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tzdata (timezones)
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas

      - name: Build modeling dataset
        env:
          BYE_THRESHOLD_DAYS: "13"
          SHORT_WEEK_MAX_DAYS: "6"
          LONG_TRIP_KM: "1500"
        run: |
          python scripts/build_modeling_dataset.py
          echo "---- head(data/modeling_dataset.csv) ----" || true
          head -n 5 data/modeling_dataset.csv || true
          echo "---- tail(logs_build_modeling_dataset.txt) ----" || true
          tail -n 100 logs_build_modeling_dataset.txt || true

      - name: Acceptance checks (bash)
        run: |
          set -e
          test -s data/modeling_dataset.csv || (echo "modeling_dataset.csv missing" && exit 1)
          IFS=',' read -r HEADER < data/modeling_dataset.csv
          echo "$HEADER" | tr ',' '\n' > headers.txt
          REQUIRED="is_home is_away is_neutral rest_days had_bye short_week travel_km long_trip_flag tz_diff_from_home east_to_west_flag west_to_east_flag body_clock_kickoff_hour altitude_game"
          for COL in $REQUIRED; do
            if ! grep -Fxq "$COL" headers.txt; then
              echo "Missing required column: $COL"; exit 1
            fi
          done
          echo "ACCEPTANCE: PASS"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modeling-dataset-and-logs
          path: |
            data/modeling_dataset.csv
            logs_build_modeling_dataset.txt
