name: Build Modeling Dataset (Situational)

on:
  workflow_dispatch:

permissions:
  contents: write   # <-- this gives the workflow permission to push commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas

      - name: Build modeling dataset
        env:
          BYE_THRESHOLD_DAYS: "13"
          SHORT_WEEK_MAX_DAYS: "6"
          LONG_TRIP_KM: "1500"
        run: |
          python scripts/build_modeling_dataset.py

      - name: Acceptance checks
        run: |
          set -e
          test -s data/modeling_dataset.csv
          header="$(head -n1 data/modeling_dataset.csv)"
          echo "$header" | tr ',' '\n' > headers.txt
          for col in is_home is_away is_neutral rest_days had_bye short_week travel_km long_trip_flag tz_diff_from_home east_to_west_flag west_to_east_flag body_clock_kickoff_hour altitude_game; do
            grep -Fxq "$col" headers.txt || { echo "Missing required column: $col"; exit 1; }
          done
          echo "ACCEPTANCE: PASS"

      - name: Commit and push dataset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add data/modeling_dataset.csv logs_build_modeling_dataset.txt || true
          git commit -m "Update modeling_dataset with situational features [skip ci]" || echo "No changes to commit"
          git push
