name: Build Modeling Dataset (Situational)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas

      - name: Build modeling dataset
        env:
          BYE_THRESHOLD_DAYS: "13"
          SHORT_WEEK_MAX_DAYS: "6"
          LONG_TRIP_KM: "1500"
        run: |
          python scripts/build_modeling_dataset.py

      - name: Acceptance checks
        shell: bash
        run: |
          set -euo pipefail
          test -s data/modeling_dataset.csv
          header="$(head -n1 data/modeling_dataset.csv)"
          printf '%s\n' "$header" | tr ',' '\n' > headers.txt
          for col in is_home is_away is_neutral rest_days had_bye short_week travel_km long_trip_flag tz_diff_from_home east_to_west_flag west_to_east_flag body_clock_kickoff_hour altitude_game; do
            grep -Fxq "$col" headers.txt || { echo "Missing required column: $col"; exit 1; }
          done
          echo "ACCEPTANCE: PASS"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modeling-dataset-and-logs
          path: |
            data/modeling_dataset.csv
            logs_build_modeling_dataset.txt
