name: Clean Stadiums Missing Coordinates

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pandas
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run cleaner
        run: |
          python scripts/clean_stadiums_missing_coords.py

      - name: Commit cleaned file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add the cleaned stadiums file
          git add data/reference/stadiums.csv

          # Force-add the summary file even though it's in .gitignore
          git add -f summaries/clean_stadiums_summary.txt

          # Commit and push only if there are actual changes
          git diff --staged --quiet || git commit -m "chore: clean stadiums missing coords [skip ci]" || echo "No changes to commit"
          git push
