name: Derive Situational Factors

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  derive-factors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run derivation
        run: |
          python scripts/derive_situational_factors.py

      - name: Commit outputs (force-add)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Always stage processed outputs and summaries (even if *.csv is ignored)
          git add -f data/processed/situational_factors.csv
          git add -f summaries/situational_factors_summary.txt

          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "derive: situational factors [skip ci]" || true
          git push || true
