name: Fill Stadiums Metadata

on:
  workflow_dispatch:
    inputs:
      min_fuzzy:
        description: "Min fuzzy match score (0-100)"
        required: false
        default: "90"
  push:
    paths:
      - "scripts/fill_stadiums_from_cfbd.py"
      - "data/reference/stadiums.csv"

jobs:
  fill:
    runs-on: ubuntu-latest
    env:
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests rapidfuzz

      - name: Fill missing lat/lon/tz/altitude
        run: |
          set -euo pipefail
          python scripts/fill_stadiums_from_cfbd.py \
            --stadiums data/reference/stadiums.csv \
            --min-fuzzy "${{ github.event.inputs.min_fuzzy || 90 }}"

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/reference/stadiums.csv
          git diff --staged --quiet || git commit -m "chore(stadiums): fill metadata from CFBD [skip ci]" || echo "No changes to commit"
          git push
