# .github/workflows/fill_from_geocodes.yml
name: Fill Stadiums from Geocoded CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  geocode_fill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run geocode fill
        run: |
          python scripts/fill_stadiums_from_geocodes.py \
            --stadiums data/reference/stadiums.csv \
            --geocodes data/reference/stadiums-geocoded.csv

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/reference/stadiums.csv
          git diff --staged --quiet || git commit -m "chore(stadiums): fill from geocoded CSV [skip ci]" || echo "No changes to commit"
          git push
