# .github/workflows/report-unmatched-scores.yml
name: Report Unmatched Scores (CFB)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scores:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dateutil requests

      - name: Ensure folders exist
        run: |
          mkdir -p data data/scores data/diagnostics

      - name: Fetch raw scores
        run: |
          set -e
          if [ -f scripts/fetch_game_scores_cfbd.py ]; then
            echo "Using scripts/fetch_game_scores_cfbd.py"
            python scripts/fetch_game_scores_cfbd.py --out data/game_scores.csv
          elif [ -f scripts/fetch_game_scores.py ]; then
            echo "Using scripts/fetch_game_scores.py"
            python scripts/fetch_game_scores.py --out data/game_scores.csv
          else
            echo "ERROR: Missing fetch script"
            exit 2
          fi
          if [ ! -s data/game_scores.csv ]; then
            echo "ERROR: data/game_scores.csv not created or empty."
            exit 3
          fi

      - name: Clean & dedupe scores
        run: |
          set -e
          if [ ! -f scripts/clean_scores_unique_by_id.py ]; then
            echo "ERROR: Missing cleaner script"
            exit 4
          fi
          python scripts/clean_scores_unique_by_id.py --in data/game_scores.csv --out data/game_scores_clean.csv
          if [ ! -s data/game_scores_clean.csv ]; then
            echo "ERROR: data/game_scores_clean.csv not created or empty."
            exit 5
          fi
          cp -f data/game_scores_clean.csv data/scores/game_scores_clean.csv
          cp -f data/game_scores_clean.csv data/scores/scores.csv
          echo "SCORES UPDATED ✅"

      - name: Commit and push artifacts
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git add -f data/game_scores.csv || true
          git add -f data/game_scores_clean.csv || true
          git add -f data/scores/game_scores_clean.csv || true
          git add -f data/scores/scores.csv || true
          git add -f data/diagnostics/*.csv 2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            git status --porcelain
          else
            git commit -m "Update scores (raw+clean) [skip ci]"
            git push origin "${GITHUB_REF_NAME:-main}"
          fi
