name: Run Regression Models (CFB)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Execute regression script
        run: |
          python scripts/run_regression_models.py
          echo '--- logs_model_regression.txt ---'
          cat logs_model_regression.txt || true
          echo '--- data/model_regression_metrics.csv (head) ---'
          head -n 10 data/model_regression_metrics.csv || true
          echo '--- model artifacts ---'
          ls -lh models || true

      - name: Commit and push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f logs_model_regression.txt data/model_regression_metrics.csv models/*.pkl
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add regression metrics and model artifacts [skip ci]"
            git push
          fi
