name: Run Regression Models (CFB)

on:
  workflow_dispatch:        # allow manual trigger
  schedule:                 # automatic weekly run
    - cron: "0 17 * * 2"    # 17:00 UTC = 12:00 PM EST on Tuesdays

permissions:
  contents: write

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn joblib requests

      - name: Fetch per-game scores (CFBD /games)
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          set -e
          python scripts/fetch_game_scores_cfbd.py
          echo "Preview of data/game_scores.csv:"
          head -n 10 data/game_scores.csv || true

      - name: Execute regression script
        env:
          TARGET_COL: points_scored
          EXCLUDE_TARGET_REGEX: '(?i)^(?!points_scored$).*(points?|scores?|margin|spread)$'
          SCORES_CSV: data/game_scores.csv
        run: |
          set -e
          python scripts/run_regression_models.py

          echo '--- logs_model_regression.txt ---'
          if [ -f logs_model_regression.txt ]; then
            cat logs_model_regression.txt
          else
            echo "logs_model_regression.txt not found."
          fi

          echo '--- data/model_regression_metrics.csv ---'
          if [ -f data/model_regression_metrics.csv ]; then
            cat data/model_regression_metrics.csv
          else
            echo "data/model_regression_metrics.csv not found."
          fi

          echo '--- data/model_regression_coeffs.csv (first 40 rows) ---'
          if [ -f data/model_regression_coeffs.csv ]; then
            head -n 40 data/model_regression_coeffs.csv
          else
            echo "data/model_regression_coeffs.csv not found."
          fi

          echo '--- model artifacts ---'
          if [ -d models ]; then
            ls -lh models || true
          else:
            echo "models/ directory not found."
          fi

      - name: Commit and push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f \
            logs_model_regression.txt \
            data/model_regression_metrics.csv \
            data/model_regression_coeffs.csv \
            models/*.pkl || true

          if git diff --cached --quiet; then
            echo "No changes to commit (artifacts unchanged)."
          else
            git commit -m "Add regression metrics, coeffs, and model artifacts [skip ci]"
            git push
