name: Run Regression Models (CFB)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn joblib

      - name: Execute regression script
        env:
          # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
          # Set this to your actual numeric target column in modeling_dataset.csv
          TARGET_COL: eff_off_overall_ppa
          # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        run: |
          set -e
          python scripts/run_regression_models.py

          echo '--- logs_model_regression.txt ---'
          if [ -f logs_model_regression.txt ]; then
            cat logs_model_regression.txt
          else
            echo "logs_model_regression.txt not found."
          fi

          echo '--- data/model_regression_metrics.csv ---'
          if [ -f data/model_regression_metrics.csv ]; then
            cat data/model_regression_metrics.csv
          else
            echo "data/model_regression_metrics.csv not found."
          fi

          echo '--- model artifacts ---'
          if [ -d models ]; then
            ls -lh models || true
          else
            echo "models/ directory not found."
          fi

      - name: Commit and push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f logs_model_regression.txt data/model_regression_metrics.csv models/*.pkl || true

          if git diff --cached --quiet; then
            echo "No changes to commit (artifacts unchanged)."
          else
            git commit -m "Add regression metrics and model artifacts [skip ci]"
            git push
          fi
