name: Sync Stadiums to Teams

on:
  workflow_dispatch:
    inputs:
      teams_csv:
        description: "Path to teams CSV (has column 'team' or 'School')"
        required: false
        default: "data/reference/teams.csv"
      schedules_csv:
        description: "Alternative: path to schedules CSV (has home_team/away_team)"
        required: false
        default: ""
  push:
    paths:
      - "scripts/sync_stadiums_to_teams.py"
      - "data/reference/teams.csv"
      - "data/games.csv"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Sync stadiums file
        run: |
          set -euo pipefail
          TEAMS="${{ github.event.inputs.teams_csv }}"
          SCHED="${{ github.event.inputs.schedules_csv }}"
          if [ -n "${SCHED}" ]; then
            python scripts/sync_stadiums_to_teams.py --stadiums data/reference/stadiums.csv --schedules "${SCHED}"
          else
            python scripts/sync_stadiums_to_teams.py --stadiums data/reference/stadiums.csv --teams "${TEAMS}"
          fi

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "chore(stadiums): sync teams [skip ci]" || echo "No changes to commit"
          git push
