name: Sync Stadiums to Teams

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas

      - name: Run sync script
        run: |
          python scripts/sync_stadiums_to_teams.py

      - name: Commit and push updated stadiums.csv
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add data/reference/stadiums.csv
          git commit -m "Sync stadiums.csv to modeling_dataset teams [skip ci]" || echo "No changes to commit"
          git push
