name: Sync Stadiums to Teams

on:
  workflow_dispatch:
  push:
    paths:
      - "scripts/sync_stadiums_to_teams.py"
      - "data/reference/teams.csv"
      - "data/reference/stadiums.csv"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Sync stadiums file
        run: |
          python scripts/sync_stadiums_to_teams.py \
            --stadiums data/reference/stadiums.csv \
            --teams data/reference/teams.csv

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "chore(stadiums): sync teams [skip ci]" || echo "No changes to commit"
          git push
