name: Update CFB Picks

on:
  workflow_dispatch:
  schedule:
    - cron: "15 12 * * *"  # 12:15 UTC daily (~08:15 ET)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate picks.json
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: |
          python scripts/generate_picks.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain picks.json)" ]]; then
            git add picks.json
            git commit -m "Update picks.json [skip ci]"
            git push
          else
            echo "No changes in picks.json"
          fi
