name: Update Player Stats

on:
  schedule:
    - cron: "45 12 * * *"   # every day at 12:45 UTC
  workflow_dispatch:
    inputs:
      year:
        required: false
        type: string
      season_type:
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run script
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          CFB_YEAR: ${{ inputs.year }}
          CFB_SEASON_TYPE: ${{ inputs.season_type }}
        run: python scripts/get_player_stats.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Update player stats [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
