name: Update Situational Factors

on:
  schedule:
    - cron: "50 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run script
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
        run: python scripts/get_situational_factors.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Update situational factors [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
