name: Update Weather (Open-Meteo)

on:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dateutil

      - name: Run Open-Meteo weather enrichment
        env:
          CFB_YEAR: ${{ env.CFB_YEAR }}
          CFB_SEASON_TYPE: ${{ env.CFB_SEASON_TYPE }}
        run: |
          python scripts/get_weather_openmeteo.py
          echo "--- weather_enriched sample ---"; head -n 10 weather_enriched.csv || true
          echo "--- log ---"; cat logs_weather_openmeteo.txt || true

      - name: Commit and push artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch origin main
          git reset --hard origin/main
          CHANGED="$(git status --porcelain weather_enriched.csv logs_weather_openmeteo.txt || true)"
          if [ -n "$CHANGED" ]; then
            git add weather_enriched.csv logs_weather_openmeteo.txt
            git commit -m "Update weather_enriched via Open-Meteo [skip ci]"
            git push origin main
          else
            echo "No changes to commit."
          fi
